BEGIN;

CREATE TABLE IF NOT EXISTS pipelines (
	pipeline_id SERIAL PRIMARY KEY,  
	project_id INTEGER REFERENCES projects (project_id) ON DELETE CASCADE NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

SELECT db_manage_updated_at('pipelines');

COMMIT;
