BEGIN;

CREATE TABLE IF NOT EXISTS projects(
	project_id SERIAL PRIMARY KEY,
	name VARCHAR (300) NOT NULL,
	feed_url VARCHAR (300) NOT NULL,
	is_enabled BOOLEAN NOT NULL DEFAULT true,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

SELECT db_manage_updated_at('projects');

COMMIT;
