BEGIN;

CREATE TABLE IF NOT EXISTS projects(
	project_id SERIAL PRIMARY KEY,
	domain VARCHAR (300) NOT NULL,
	feed_url VARCHAR (300) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

SELECT db_manage_updated_at('projects');

COMMIT;
