version: '3'

services:
  newsletter:
    image: "statictask/newsletter:devel"
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    command:
    - "server"
    volumes:
    - .:/app
    ports:
      - 8080:8080
    environment:
      NEWSLETTER_POSTGRES_HOST: postgres
      NEWSLETTER_POSTGRES_PORT: "5432"
      NEWSLETTER_POSTGRES_DATABASE: newsletter
      NEWSLETTER_POSTGRES_USERNAME: newsletter
      NEWSLETTER_POSTGRES_PASSWORD: newsletter
      NEWSLETTER_BIND_ADDRESS: 0.0.0.0:8080
    depends_on:
    - postgres
  postgres:
    image: postgres:14.3
    environment:
      POSTGRES_DB: newsletter
      POSTGRES_USER: newsletter
      POSTGRES_PASSWORD: newsletter
    ports:
    - 5432:5432
    volumes:
    - newsletter_db_data:/var/lib/postgresql/data

volumes:
  newsletter_db_data: {}
