apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-config
data:
  newsletterPostgresHost: {{ .Values.config.postgres.host | b64enc }}
  newsletterPostgresPort: {{ printf "%d" .Values.config.postgres.port | b64enc }}
  newsletterPostgresDatabase: {{ .Values.config.postgres.database | b64enc }}
  newsletterPostgresUsername: {{ .Values.config.postgres.username | b64enc }}
  newsletterPostgresPassword: {{ .Values.config.postgres.password | b64enc }}
  newsletterBindAddress: {{ .Values.config.server.bindAddress | b64enc }}
